version: "3.5"

services:
  webserver:
    container_name: time_report_apache
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./app:/var/www/html
      - ./:/var/www